version: '3'
services:
  redis:
    image: 'redis:5.0.4-alpine'
    restart: unless-stopped
    logging:
      driver: none
  server:
    restart: unless-stopped
    build:
      dockerfile: ./fixtures/bull-server/server/Dockerfile
    ports:
      - 3000:3000
    environment:
      - ENVIRONMENT=local
      - BULL_REDIS_HOST=172.20.0.71,172.20.0.72,172.20.0.73
      - BULL_REDIS_PORT=6381,6382,6383
      - REDIS_PW_BULL=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - QUEUES=metrics_queue,tagging_queue,dynamodb_account_queue,assume_account_queue,describe_queue
      - PREFIXES={bull_metrics},{bull_tagging},{bull_dynamodb},{bull_assumer},{bull_describer}
      - PORT=3000
    depends_on:
      - redis-bullcluster-node-1
      - redis-bullcluster-node-2
      - redis-bullcluster-node-3
    # depends_on:
    #   - redis
    # volumes:
    #   - ./server:/app
    #   - ../../packages/root:/packages/root
    #   - ../../packages/express:/packages/express
